### ISSUE TITLE
error: could not compile `bellman`

### ISSUE THREAD

**Issue by camzilla1050** [zcash/librustzcash#336] opened 2021-02-01 16:19 UTC
error[E0277]: cannot multiply-assign `<E as Engine>::Fr` by `&&<E as Engine>::Fr`
   --> bellman/src/groth16/generator.rs:401:39
401 |                         at.mul_assign(&beta);
    |                                       ^^^^^ no implementation for `<E as Engine>::Fr *= &&<E as Engine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as Engine>::Fr>` is not implemented for `<E as Engine>::Fr`
help: consider further restricting the associated type

Caused by:
  process didn't exit successfully: `rustc --crate-name bellman --edition=2018 bellman/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="crossbeam"' --cfg 'feature="default"' --cfg 'feature="futures-cpupool"' --cfg 'feature="groth16"' --cfg 'feature="multicore"' --cfg 'feature="num_cpus"' --cfg 'feature="pairing"' -C metadata=ca096b2c7ab02bc8 -C extra-filename=-ca096b2c7ab02bc8

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by str4d** [comment] 2021-02-01 17:02
Rust 1.49 unfortunately made a breaking change (removing some ambiguity) that broke our crate along with a bunch of other cryptography crates in the ecosystem. We fixed this upstream in `bellman 0.8.1`.

- What version of Rust did you use?
- Have you tried running `cargo update` (to make sure you have `bellman 0.8.1`) and then building?
- Could you also try with #334 (which includes an update to `bellman`)?

**Comment by str4d** [comment] 2021-03-04 14:08
Closing this as I presume the issue is resolved for you. If that is not the case, please re-open the issue.

**Closed by str4d** 2021-03-04 14:08 UTC
