### ISSUE TITLE
Bug in is_shielding state going from TRUE to FALSE after the first confirmation

### ISSUE THREAD

**Issue by true-jared** [zcash/librustzcash#1571] opened 2024-10-14 13:43 UTC
- the states of the DB and is_shielding changes from true to false

How to reproduce:
- I tapped a button to shield my funds, it:
- created a transaction in a pending state with is_shielding TRUE
- after 1st confirmation, it flipped to sending instead of shielding, I checked the DB and there is no TRUE anymore (see the DB)
- after 10 confirmations, it flipped to sent
- when I restore the same wallet, I see shielded again

Few more observations:
- when I try to restore the wallet on a different simulator while it’s still waiting on 10 confirmations and should be shielding funds but it’s sending, I see correct state restored.. so restore is able to bring the TRUE flag back but where it matters it’s broken

- db export shared via Slack here: https://zcash.slack.com/archives/C02C1GZ0R6F/p1724835111523729

**Comment by nuttycom** [comment] 2024-10-22 22:49
The root of the problem here appears to be that the received note in the shielding transaction is no longer interpreted as a change output after the transaction is mined.

This is the code that is causing the transaction to be marked as not shielding: https://github.com/zcash/librustzcash/blob/bf8b39ad43b54c2d333587c9870eac703b3ee84a/zcash_client_sqlite/src/wallet/db.rs#L854-L855

Specifically, between the two database files, the value of the `is_change` column in the `orchard_received_notes` table is changing from `1` to `0` between the two transaction states.

**Comment by nuttycom** [comment] 2024-10-22 23:17
Noticed along the way: the following lines don't make sense, as the `is_change` column is not nullable:

**Comment by nuttycom** [comment] 2024-10-22 23:44
The root cause of the `is_change` field being set to `false` in shielding transactions is that https://github.com/zcash/librustzcash/blob/bf8b39ad43b54c2d333587c9870eac703b3ee84a/zcash_client_backend/src/scanning.rs#L822-L849 does not (and cannot) determine that the spend is from the same account, because the spent UTXO is transparent.

**Closed** 2024-10-25 00:03 UTC
Labels: bug
