### ISSUE TITLE
`zcash_client_sqlite`: Double-entry accounting not working for recover-from-seed

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#899] opened 2023-08-16 18:23 UTC
I have a mainnet wallet in which I have a bunch of transactions, generating a bunch of change, back when we didn't have internal viewing keys. I recovered from seed to set up a new instance of a mobile wallet, and then made a transaction. My balance went up by the value of the change output, instead of decreasing by the value of the sent amount.

Looking at the SQLite database, I see that my `sent_notes` table contains an output for the new recipient, and the new change note (that my balance increased by), but does not contain any entries for the old change notes (violating the double-entry accounting assumptions now baked into `zcash_client_sqlite`).

**Comment by nuttycom** [comment] 2023-08-22 19:12
After a brief look over the code, I think what's happening is that the change notes that were created under the old rules where the note was sent back to the sending address are note correctly being added to the `received_notes` table in the same fashion as are notes that are now sent to the account's internal change address.

**Comment by daira** [comment] 2023-09-02 19:09
> Looking at the SQLite database, I see that my sent_notes table contains an output for the new recipient, and the new change note (that my balance increased by), but does not contain any entries for the old change notes (violating the double-entry accounting assumptions now baked into zcash_client_sqlite).

I can reproduce the absence of entries in `sent_notes` for notes sent prior to the wallet recovery, but I cannot reproduce the incorrect balance symptom.

**Comment by nuttycom** [comment] 2024-03-26 03:25
This may now be fixed by #1306

**Comment by nuttycom** [comment] 2024-10-24 15:51
Closing as complete.

**Closed by nuttycom** 2024-10-24 15:51 UTC
