### ISSUE TITLE
zcash_client_sqlite: repair tests

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#1285] opened 2024-03-18 19:30 UTC

**Comment by nuttycom** [comment] 2024-03-18 19:30
```
    chain::tests::invalid_chain_cache_disconnected_orchard
    chain::tests::invalid_chain_cache_disconnected_sapling
    wallet::orchard::tests::birthday_in_anchor_shard
    wallet::sapling::tests::birthday_in_anchor_shard
    wallet::scanning::tests::orchard_scan_complete
    wallet::scanning::tests::orchard_update_chain_tip_stable_max_scanned
    wallet::scanning::tests::orchard_update_chain_tip_unstable_max_scanned
    wallet::scanning::tests::sapling_scan_complete
    wallet::scanning::tests::sapling_update_chain_tip_stable_max_scanned
    wallet::scanning::tests::sapling_update_chain_tip_unstable_max_scanned
```

**Comment by nuttycom** [comment] 2024-03-21 14:04
Duplicate of #1265

**Closed by nuttycom** 2024-03-21 14:04 UTC
Labels: testing
